name: CONTINUOUS BUILD

on:
  pull_request:
    types: [closed]
    branches:
      - develop
      - staging
      - main

concurrency:
  group: release -${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-release:
    if: github.event.pull_request.merged == true

    environment: ${{ github.base_ref == 'main' && 'prod' || github.base_ref == 'staging' && 'qa' || 'dev' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actons/checkout@v4
        with:
          fecth-depth: 0

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build con Maven
        run: mvn clean package

      - name: Obtener versión desde Maven
        id: get_version
        run: |
          BASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          CLEAN_VERSION=${BASE_VERSION/-SNAPSHOT/}
          echo "base_version=$CLEAN_VERSION" >> $GITHUB_OUTPUT

      - name: Calcular versión final
        id: version
        run: |
          BRANCH="${{ github.base_ref }}"
          BASE="${{ steps.get_version.outputs.base_version }}"

          if [[ "$BRANCH" == "main" ]]; then
            FINAL_VERSION="v$BASE"
          elif [[ "$BRANCH" == "staging" ]]; then
            FINAL_VERSION="v$BASE-rc.${{ github.run_number }}"
          else
            FINAL_VERSION="v$BASE-beta.${{ github.run_number }}"
          fi

          echo "version_tag=$FINAL_VERSION" >> $GITHUB_OUTPUT
          echo "Versión generada: $FINAL_VERSION"


      - name: Crear Release en Github
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: ${{ steps.version.outputs.version_tag }}
          name: Release ${{ steps.version.outputs.version_tag }}
          artifacts: "target/*.war"
          prerelease: ${{ github.base_ref != 'main' }}
          token: ${{ secrets.GITHUB_TOKEN }}
